/*
 * BSD 2-Clause License
 *
 * Copyright (c) 2021, Riley McGee
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.wastedbankspace.model.locations;

import com.wastedbankspace.model.StorageLocation;
import net.runelite.api.ItemID;

import java.util.Set;

public class ArmourCase implements StorageLocation {

    private static final Set<Integer> ITEMS = Set.of(
            ItemID.ADVENTURERS_HOOD_T1,
            ItemID.ADVENTURERS_TOP_T1,
            ItemID.ADVENTURERS_TROUSERS_T1,
            ItemID.ADVENTURERS_BOOTS_T1,
            ItemID.ADVENTURERS_HOOD_T2,
            ItemID.ADVENTURERS_TOP_T2,
            ItemID.ADVENTURERS_TROUSERS_T2,
            ItemID.ADVENTURERS_BOOTS_T2,
            ItemID.ADVENTURERS_HOOD_T3,
            ItemID.ADVENTURERS_TOP_T3,
            ItemID.ADVENTURERS_TROUSERS_T3,
            ItemID.ADVENTURERS_BOOTS_T3,
            // Angler outfit is storable in the tackle box
            // Spirit angler outfit is storable in the tackle box
            ItemID.ARDOUGNE_KNIGHT_HELM,
            ItemID.ARDOUGNE_KNIGHT_PLATEBODY,
            ItemID.ARDOUGNE_KNIGHT_PLATELEGS,
            ItemID.BOMBER_CAP,
            ItemID.CAP_AND_GOGGLES,
            ItemID.BOMBER_JACKET,
            ItemID.HARD_HAT,
            ItemID.BUILDERS_SHIRT,
            ItemID.BUILDERS_TROUSERS,
            ItemID.BUILDERS_BOOTS,
            ItemID.DESERT_CAMO_TOP,
            ItemID.DESERT_CAMO_LEGS,
            ItemID.JUNGLE_CAMO_TOP,
            ItemID.JUNGLE_CAMO_LEGS,
            ItemID.POLAR_CAMO_TOP,
            ItemID.POLAR_CAMO_LEGS,
            ItemID.WOOD_CAMO_TOP,
            ItemID.WOOD_CAMO_LEGS,
            ItemID.SHATTERED_CANE,
            ItemID.TRAILBLAZER_CANE,
            ItemID.TWISTED_CANE,
            // Castle Wars armour (1)
            ItemID.DECORATIVE_HELM,
            ItemID.DECORATIVE_FULL_HELM,
            ItemID.DECORATIVE_ARMOUR,
            ItemID.DECORATIVE_ARMOUR_4070,
            ItemID.DECORATIVE_ARMOUR_11893,
            ItemID.DECORATIVE_SHIELD,
            ItemID.DECORATIVE_BOOTS,
            // Castle Wars armour (2)
            ItemID.DECORATIVE_HELM_4506,
            ItemID.DECORATIVE_FULL_HELM_25169,
            ItemID.DECORATIVE_ARMOUR_4504,
            ItemID.DECORATIVE_ARMOUR_4505,
            ItemID.DECORATIVE_ARMOUR_11894,
            ItemID.DECORATIVE_SHIELD_4507,
            ItemID.DECORATIVE_BOOTS_25167,
            // Castle Wars armour (3)
            ItemID.DECORATIVE_HELM_4511,
            ItemID.DECORATIVE_FULL_HELM_25174,
            ItemID.DECORATIVE_ARMOUR_4509,
            ItemID.DECORATIVE_ARMOUR_4510,
            ItemID.DECORATIVE_ARMOUR_11895,
            ItemID.DECORATIVE_SHIELD_4512,
            ItemID.DECORATIVE_BOOTS_25171,
            // Castle Wars sword (1)
            ItemID.DECORATIVE_SWORD,
            // Castle Wars sword (2)
            ItemID.DECORATIVE_SWORD_4503,
            // Castle Wars sword (3)
            ItemID.DECORATIVE_SWORD_4508,
            // Castle Wars mage armour
            ItemID.DECORATIVE_ARMOUR_11896,
            ItemID.DECORATIVE_ARMOUR_11897,
            ItemID.DECORATIVE_ARMOUR_11898,
            // Castle Wars ranger armour
            ItemID.DECORATIVE_ARMOUR_11899,
            ItemID.DECORATIVE_ARMOUR_11900,
            ItemID.DECORATIVE_ARMOUR_11901,
            ItemID.CLUE_HUNTER_GARB,
            ItemID.CLUE_HUNTER_TROUSERS,
            ItemID.CLUE_HUNTER_GLOVES,
            ItemID.CLUE_HUNTER_BOOTS,
            ItemID.CLUE_HUNTER_CLOAK,
            ItemID.CORRUPTED_HELM,
            ItemID.CORRUPTED_PLATEBODY,
            ItemID.CORRUPTED_PLATELEGS,
            ItemID.CORRUPTED_PLATESKIRT,
            ItemID.CORRUPTED_KITESHIELD,
            ItemID.DEADMANS_CHEST,
            ItemID.DEADMANS_LEGS,
            ItemID.DEADMANS_CAPE,
            ItemID.DRAGONSTONE_FULL_HELM,
            ItemID.DRAGONSTONE_PLATEBODY,
            ItemID.DRAGONSTONE_PLATELEGS,
            ItemID.DRAGONSTONE_BOOTS,
            ItemID.DRAGONSTONE_GAUNTLETS,
            ItemID.FARMERS_STRAWHAT,
            ItemID.FARMERS_JACKET,
            ItemID.FARMERS_SHIRT,
            ItemID.FARMERS_BORO_TROUSERS,
            ItemID.FARMERS_BOOTS,
            ItemID.FEDORA,
            ItemID.GIANT_STOPWATCH,
            ItemID.HAM_HOOD,
            ItemID.HAM_SHIRT,
            ItemID.HAM_ROBE,
            ItemID.HAM_GLOVES,
            ItemID.HAM_BOOTS,
            ItemID.HAM_CLOAK,
            ItemID.HAM_LOGO,
            ItemID.ANCIENT_HALO,
            ItemID.ARMADYL_HALO,
            ItemID.BANDOS_HALO,
            ItemID.BRASSICA_HALO,
            ItemID.GUTHIX_HALO,
            ItemID.SARADOMIN_HALO,
            ItemID.SEREN_HALO,
            ItemID.ZAMORAK_HALO,
            ItemID.HELM_OF_RAEDWALD,
            ItemID.GRAAHK_HEADDRESS,
            ItemID.GRAAHK_TOP,
            ItemID.GRAAHK_LEGS,
            ItemID.KYATT_HAT,
            ItemID.KYATT_TOP,
            ItemID.KYATT_LEGS,
            ItemID.LARUPIA_HAT,
            ItemID.LARUPIA_TOP,
            ItemID.LARUPIA_LEGS,
            ItemID.INQUISITORS_GREAT_HELM,
            ItemID.INQUISITORS_HAUBERK,
            ItemID.INQUISITORS_PLATESKIRT,
            ItemID.JUSTICIAR_FACEGUARD,
            ItemID.JUSTICIAR_CHESTGUARD,
            ItemID.JUSTICIAR_LEGGUARDS,
            ItemID.LUMBERJACK_HAT,
            ItemID.LUMBERJACK_TOP,
            ItemID.LUMBERJACK_LEGS,
            ItemID.LUMBERJACK_BOOTS,
            ItemID.MASORI_MASK,
            ItemID.MASORI_BODY,
            ItemID.MASORI_CHAPS,
            ItemID.MASORI_MASK_F,
            ItemID.MASORI_BODY_F,
            ItemID.MASORI_CHAPS_F,
            ItemID.MINING_GLOVES,
            ItemID.SUPERIOR_MINING_GLOVES,
            ItemID.EXPERT_MINING_GLOVES,
            ItemID.MIXED_HIDE_TOP,
            ItemID.MIXED_HIDE_LEGS,
            ItemID.MIXED_HIDE_BOOTS,
            ItemID.MIXED_HIDE_CAPE,
            ItemID.GAS_MASK,
            ItemID.MOURNER_TOP,
            ItemID.MOURNER_TROUSERS,
            ItemID.MOURNER_BOOTS,
            ItemID.MOURNER_GLOVES,
            ItemID.MOURNER_CLOAK,
            ItemID.OBSIDIAN_HELMET,
            ItemID.OBSIDIAN_PLATEBODY,
            ItemID.OBSIDIAN_PLATELEGS,
            ItemID.ORNATE_HELM,
            ItemID.ORNATE_TOP,
            ItemID.ORNATE_LEGS,
            ItemID.ORNATE_GLOVES,
            ItemID.ORNATE_BOOTS,
            ItemID.ORNATE_CAPE,
            ItemID.FIGHTER_HAT,
            ItemID.FIGHTER_TORSO,
            ItemID.PENANCE_GLOVES,
            ItemID.HEALER_HAT,
            ItemID.RANGER_HAT,
            ItemID.RUNNER_BOOTS,
            ItemID.RUNNER_HAT,
            ItemID.PENANCE_SKIRT,
            ItemID.PROSPECTOR_HELMET,
            ItemID.PROSPECTOR_JACKET,
            ItemID.PROSPECTOR_LEGS,
            ItemID.PROSPECTOR_BOOTS,
            ItemID.GOLDEN_PROSPECTOR_HELMET,
            ItemID.GOLDEN_PROSPECTOR_JACKET,
            ItemID.GOLDEN_PROSPECTOR_LEGS,
            ItemID.GOLDEN_PROSPECTOR_BOOTS,
            ItemID.ROCKSHELL_HELM,
            ItemID.ROCKSHELL_PLATE,
            ItemID.ROCKSHELL_LEGS,
            ItemID.ROCKSHELL_GLOVES,
            ItemID.ROCKSHELL_BOOTS,
            ItemID.ROGUE_MASK,
            ItemID.ROGUE_TOP,
            ItemID.ROGUE_GLOVES,
            ItemID.ROGUE_TROUSERS,
            ItemID.ROGUE_BOOTS,
            ItemID.SHATTERED_HOOD_T1,
            ItemID.SHATTERED_TOP_T1,
            ItemID.SHATTERED_TROUSERS_T1,
            ItemID.SHATTERED_BOOTS_T1,
            ItemID.SHATTERED_HOOD_T2,
            ItemID.SHATTERED_TOP_T2,
            ItemID.SHATTERED_TROUSERS_T2,
            ItemID.SHATTERED_BOOTS_T2,
            ItemID.SHATTERED_HOOD_T3,
            ItemID.SHATTERED_TOP_T3,
            ItemID.SHATTERED_TROUSERS_T3,
            ItemID.SHATTERED_BOOTS_T3,
            ItemID.SHAYZIEN_HELM_1,
            ItemID.SHAYZIEN_PLATEBODY_1,
            ItemID.SHAYZIEN_GREAVES_1,
            ItemID.SHAYZIEN_GLOVES_1,
            ItemID.SHAYZIEN_BOOTS_1,
            ItemID.SHAYZIEN_HELM_2,
            ItemID.SHAYZIEN_PLATEBODY_2,
            ItemID.SHAYZIEN_GREAVES_2,
            ItemID.SHAYZIEN_GLOVES_2,
            ItemID.SHAYZIEN_BOOTS_2,
            ItemID.SHAYZIEN_HELM_3,
            ItemID.SHAYZIEN_PLATEBODY_3,
            ItemID.SHAYZIEN_GREAVES_3,
            ItemID.SHAYZIEN_GLOVES_3,
            ItemID.SHAYZIEN_BOOTS_3,
            ItemID.SHAYZIEN_HELM_4,
            ItemID.SHAYZIEN_PLATEBODY_4,
            ItemID.SHAYZIEN_GREAVES_4,
            ItemID.SHAYZIEN_GLOVES_4,
            ItemID.SHAYZIEN_BOOTS_4,
            ItemID.SHAYZIEN_HELM_5,
            ItemID.SHAYZIEN_BODY_5,
            ItemID.SHAYZIEN_GREAVES_5,
            ItemID.SHAYZIEN_GLOVES_5,
            ItemID.SHAYZIEN_BOOTS_5,
            ItemID.SNAKESKIN_BANDANA,
            ItemID.SNAKESKIN_BODY,
            ItemID.SNAKESKIN_BOOTS,
            ItemID.SNAKESKIN_CHAPS,
            ItemID.SNAKESKIN_VAMBRACES,
            ItemID.SPINED_HELM,
            ItemID.SPINED_BODY,
            ItemID.SPINED_CHAPS,
            ItemID.SPINED_GLOVES,
            ItemID.SPINED_BOOTS,
            ItemID.FANCY_BOOTS,
            ItemID.FIGHTING_BOOTS,
            ItemID.FANCIER_BOOTS,
            ItemID.SUNFIRE_FANATIC_HELM,
            ItemID.SUNFIRE_FANATIC_CUIRASS,
            ItemID.SUNFIRE_FANATIC_CHAUSSES,
            ItemID.SWIFT_BLADE,
            ItemID.INITIATE_SALLET,
            ItemID.INITIATE_HAUBERK,
            ItemID.INITIATE_CUISSE,
            ItemID.PROSELYTE_SALLET,
            ItemID.PROSELYTE_HAUBERK,
            ItemID.PROSELYTE_CUISSE,
            ItemID.TRAILBLAZER_HOOD_T1,
            ItemID.TRAILBLAZER_TOP_T1,
            ItemID.TRAILBLAZER_TROUSERS_T1,
            ItemID.TRAILBLAZER_BOOTS_T1,
            ItemID.TRAILBLAZER_HOOD_T2,
            ItemID.TRAILBLAZER_TOP_T2,
            ItemID.TRAILBLAZER_TROUSERS_T2,
            ItemID.TRAILBLAZER_BOOTS_T2,
            ItemID.TRAILBLAZER_HOOD_T3,
            ItemID.TRAILBLAZER_TOP_T3,
            ItemID.TRAILBLAZER_TROUSERS_T3,
            ItemID.TRAILBLAZER_BOOTS_T3,
            ItemID.TRIBAL_MASK,
            ItemID.TRIBAL_MASK_6337,
            ItemID.TRIBAL_MASK_6339,
            ItemID.TWISTED_HAT_T1,
            ItemID.TWISTED_COAT_T1,
            ItemID.TWISTED_TROUSERS_T1,
            ItemID.TWISTED_BOOTS_T1,
            ItemID.TWISTED_HAT_T2,
            ItemID.TWISTED_COAT_T2,
            ItemID.TWISTED_TROUSERS_T2,
            ItemID.TWISTED_BOOTS_T2,
            ItemID.TWISTED_HAT_T3,
            ItemID.TWISTED_COAT_T3,
            ItemID.TWISTED_TROUSERS_T3,
            ItemID.TWISTED_BOOTS_T3,
            ItemID.VOID_KNIGHT_TOP,
            ItemID.VOID_KNIGHT_ROBE,
            ItemID.VOID_KNIGHT_GLOVES,
            ItemID.VOID_KNIGHT_TOP_OR,
            ItemID.VOID_KNIGHT_ROBE_OR,
            ItemID.VOID_KNIGHT_GLOVES_OR,
            ItemID.ELITE_VOID_TOP,
            ItemID.ELITE_VOID_ROBE,
            ItemID.ELITE_VOID_TOP_OR,
            ItemID.ELITE_VOID_ROBE_OR,
            ItemID.VOID_MAGE_HELM,
            ItemID.VOID_MAGE_HELM_OR,
            ItemID.VOID_MELEE_HELM,
            ItemID.VOID_MELEE_HELM_OR,
            ItemID.VOID_RANGER_HELM,
            ItemID.VOID_RANGER_HELM_OR,
            ItemID.VYRE_NOBLE_TOP,
            ItemID.VYRE_NOBLE_LEGS,
            ItemID.VYRE_NOBLE_SHOES,
            ItemID.WHITE_FULL_HELM,
            ItemID.WHITE_PLATEBODY,
            ItemID.WHITE_PLATESKIRT,
            ItemID.WHITE_PLATELEGS,
            ItemID.WHITE_GLOVES,
            ItemID.WHITE_BOOTS,
            ItemID.WHITE_KITESHIELD,
            ItemID.XERICIAN_HAT,
            ItemID.XERICIAN_TOP,
            ItemID.XERICIAN_ROBE,
            ItemID.ELITE_BLACK_FULL_HELM,
            ItemID.ELITE_BLACK_PLATEBODY,
            ItemID.ELITE_BLACK_PLATELEGS,
            ItemID.PRESCRIPTION_GOGGLES,
            ItemID.ALCHEMIST_LABCOAT,
            ItemID.ALCHEMIST_GLOVES,
            ItemID.ALCHEMIST_PANTS
    );

    @Override
    public String getName() {
        return "Armour Case";
    }

    @Override
    public Set<Integer> getStorableItems() {
        return ITEMS;
    }
}
