/*
 * BSD 2-Clause License
 *
 * Copyright (c) 2021, Riley McGee
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.wastedbankspace.model.locations;

import com.wastedbankspace.model.StorableItem;
import lombok.Getter;
import net.runelite.api.ItemID;

@Getter
public enum Bookcase implements StorableItem {
    A_DEAR_FRIEND(ItemID.A_DEAR_FRIEND),
    A_HANDWRITTEN_BOOK(ItemID.A_HANDWRITTEN_BOOK),
    A_TASTE_OF_HOPE(ItemID.A_TASTE_OF_HOPE),
    ABLENKIANS_ESCAPE(ItemID.ABLENKIANS_ESCAPE),
    ABYSSAL_BOOK(ItemID.ABYSSAL_BOOK),
    AIVAS_DIARY(ItemID.AIVAS_DIARY),
    AKILAS_JOURNAL(ItemID.AKILAS_JOURNAL),
    ANCIENT_DIARY(ItemID.ANCIENT_DIARY),
    APMEKENS_CAPTURE(ItemID.APMEKENS_CAPTURE),
    ARACHNIDS_OF_VAMPYRIUM(ItemID.ARACHNIDS_OF_VAMPYRIUM),
    ARCHAEOLOGISTS_DIARY(ItemID.ARCHAEOLOGISTS_DIARY),
    ARENA_BOOK(ItemID.ARENA_BOOK),
    ASTRONOMY_BOOK(ItemID.ASTRONOMY_BOOK),
    ATLAXS_DIARY(ItemID.ATLAXS_DIARY),
    AUBURN_VALLEY_ECOLOGICAL_REPORTS(ItemID.AUBURN_VALLEY_ECOLOGICAL_REPORTS),
    BALLAD_OF_THE_BASILISK(ItemID.BALLAD_OF_THE_BASILISK),
    BATTERED_BOOK(ItemID.BATTERED_BOOK),
    BEATEN_BOOK(ItemID.BEATEN_BOOK),
    BIG_BOOK_OF_BANGS(ItemID.BIG_BOOK_OF_BANGS),
    BINDING_BOOK(ItemID.BINDING_BOOK),
    BIRD_BOOK(ItemID.BIRD_BOOK),
    BLOODY_DIARY(ItemID.BLOODY_DIARY),
    BLOODY_NOTES(ItemID.BLOODY_NOTES),
    BOOK(ItemID.BOOK),
    BOOK_6767(ItemID.BOOK_6767),
    BOOK_O_PIRACY(ItemID.BOOK_O_PIRACY),
    BOOK_OF_SPYOLOGY(ItemID.BOOK_OF_SPYOLOGY),
    BOOK_ON_BAXTORIAN(ItemID.BOOK_ON_BAXTORIAN),
    BOOK_ON_CHEMICALS(ItemID.BOOK_ON_CHEMICALS),
    BREWIN_GUIDE(ItemID.BREWIN_GUIDE),
    BURNT_DIARY(ItemID.BURNT_DIARY),
    CADARN_LINEAGE(ItemID.CADARN_LINEAGE),
    CLOCKWORK_BOOK(ItemID.CLOCKWORK_BOOK),
    COCKTAIL_GUIDE(ItemID.COCKTAIL_GUIDE),
    COLLECTION_LOG(ItemID.COLLECTION_LOG),
    CONSTRUCTION_GUIDE(ItemID.CONSTRUCTION_GUIDE),
    CRAZED_SCRIBBLES(ItemID.CRAZED_SCRIBBLES),
    CREATURE_KEEPERS_JOURNAL(ItemID.CREATURE_KEEPERS_JOURNAL),
    CRONDIS_CAPTURE(ItemID.CRONDIS_CAPTURE),
    CRUMBLING_TOME(ItemID.CRUMBLING_TOME),
    CRYSTAL_SINGING_FOR_BEGINNERS(ItemID.CRYSTAL_SINGING_FOR_BEGINNERS),
    DAGONHAI_HISTORY(ItemID.DAGONHAI_HISTORY),
    DARK_JOURNAL(ItemID.DARK_JOURNAL),
    DEMONIC_TOME(ItemID.DEMONIC_TOME),
    DIARY(ItemID.DIARY),
    DIARY_3395(ItemID.DIARY_3395),
    DIARY_3846(ItemID.DIARY_3846),
    DWARVEN_LORE(ItemID.DWARVEN_LORE),
    EASTERN_DISCOVERY(ItemID.EASTERN_DISCOVERY),
    EASTERN_SETTLEMENT(ItemID.EASTERN_SETTLEMENT),
    EBRILLS_JOURNAL(ItemID.EBRILLS_JOURNAL),
    EDERNS_JOURNAL(ItemID.EDERNS_JOURNAL),
    EMBALMING_MANUAL(ItemID.EMBALMING_MANUAL),
    ENTOMOLOGISTS_DIARY(ItemID.ENTOMOLOGISTS_DIARY),
    EXPLORERS_NOTES(ItemID.EXPLORERS_NOTES),
    FARMING_MANUAL(ItemID.FARMING_MANUAL),
    FEATHERED_JOURNAL(ItemID.FEATHERED_JOURNAL),
    FOSSIL_ISLAND_NOTE_BOOK(ItemID.FOSSIL_ISLAND_NOTE_BOOK),
    GAME_BOOK(ItemID.GAME_BOOK),
    GHRIMS_BOOK(ItemID.GHRIMS_BOOK),
    GIANNES_COOK_BOOK(ItemID.GIANNES_COOK_BOOK),
    GIELINORS_FLORA__ALLOTMENTS(ItemID.GIELINORS_FLORA__ALLOTMENTS),
    GIELINORS_FLORA__BUSHES(ItemID.GIELINORS_FLORA__BUSHES),
    GIELINORS_FLORA__FLOWERS(ItemID.GIELINORS_FLORA__FLOWERS),
    GIELINORS_FLORA__FRUIT(ItemID.GIELINORS_FLORA__FRUIT),
    GIELINORS_FLORA__HERBS(ItemID.GIELINORS_FLORA__HERBS),
    GIELINORS_FLORA__HOPS(ItemID.GIELINORS_FLORA__HOPS),
    GIELINORS_FLORA__TREES(ItemID.GIELINORS_FLORA__TREES),
    GLASSBLOWING_BOOK(ItemID.GLASSBLOWING_BOOK),
    GLOUGHS_JOURNAL(ItemID.GLOUGHS_JOURNAL),
    GOBLIN_BOOK(ItemID.GOBLIN_BOOK),
    GOBLIN_SYMBOL_BOOK(ItemID.GOBLIN_SYMBOL_BOOK),
    GOLLWYNS_FINAL_STATEMENT(ItemID.GOLLWYNS_FINAL_STATEMENT),
    GUIDE_BOOK(ItemID.GUIDE_BOOK),
    HARMONY(ItemID.HARMONY),
    HERMANS_BOOK(ItemID.HERMANS_BOOK),
    HETS_CAPTURE(ItemID.HETS_CAPTURE),
    HISTORIES_OF_THE_HALLOWLAND(ItemID.HISTORIES_OF_THE_HALLOWLAND),
    HISTORY_OF_IBAN(ItemID.HISTORY_OF_IBAN),
    HOUNDMASTERS_DIARY(ItemID.HOUNDMASTERS_DIARY),
    IMAFORES_BETRAYAL(ItemID.IMAFORES_BETRAYAL),
    IMCANDORIAS_FALL(ItemID.IMCANDORIAS_FALL),
    INSTRUCTION_MANUAL(ItemID.INSTRUCTION_MANUAL),
    JOURNAL_3845(ItemID.JOURNAL_3845),
    JOURNAL_6755(ItemID.JOURNAL_6755),
    KASONDES_JOURNAL(ItemID.KASONDES_JOURNAL),
    LEGENDS_OF_THE_MOUNTAIN(ItemID.LEGENDS_OF_THE_MOUNTAIN),
    LITHKREN_VAULT_NOTES(ItemID.LITHKREN_VAULT_NOTES),
    LUTWIDGE_AND_THE_MOONFLY(ItemID.LUTWIDGE_AND_THE_MOONFLY),
    MALUMACS_JOURNAL(ItemID.MALUMACS_JOURNAL),
    MANUAL(ItemID.MANUAL),
    MODERN_DAY_MORYTANIA(ItemID.MODERN_DAY_MORYTANIA),
    MOONCLAN_MANUAL(ItemID.MOONCLAN_MANUAL),
    MOONRISE_WINES(ItemID.MOONRISE_WINES),
    MOUNT_KARUULM_DIARY(ItemID.MOUNT_KARUULM_DIARY),
    MOVARIOS_NOTES_VOLUME_1(ItemID.MOVARIOS_NOTES_VOLUME_1),
    MOVARIOS_NOTES_VOLUME_2(ItemID.MOVARIOS_NOTES_VOLUME_2),
    MY_NOTES(ItemID.MY_NOTES),
    NEILANS_JOURNAL(ItemID.NEILANS_JOURNAL),
    NIFF__HARRY(ItemID.NIFF__HARRY),
    NISTIRIOS_MANIFESTO(ItemID.NISTIRIOS_MANIFESTO),
    ODE_TO_ETERNITY(ItemID.ODE_TO_ETERNITY),
    OHNS_DIARY(ItemID.OHNS_DIARY),
    OLD_DIARY(ItemID.OLD_DIARY),
    OLD_JOURNAL(ItemID.OLD_JOURNAL),
    ON_LEPRECHAUNS(ItemID.ON_LEPRECHAUNS),
    ON_MIGRATION_PATTERNS(ItemID.ON_MIGRATION_PATTERNS),
    OVERSEERS_BOOK(ItemID.OVERSEERS_BOOK),
    PIE_RECIPE_BOOK(ItemID.PIE_RECIPE_BOOK),
    PRAYER_BOOK(ItemID.PRAYER_BOOK),
    PRIFDDINAS_HISTORY(ItemID.PRIFDDINAS_HISTORY),
    QUEEN_HELP_BOOK(ItemID.QUEEN_HELP_BOOK),
    SACRAMENTS_OF_ENT_FOLK(ItemID.SACRAMENTS_OF_ENT_FOLK),
    SCABARAS_CAPTURE(ItemID.SCABARAS_CAPTURE),
    SECURITY_BOOK(ItemID.SECURITY_BOOK),
    SERAFINA(ItemID.SERAFINA),
    SERAFINAS_DIARY(ItemID.SERAFINAS_DIARY),
    SHAMANS_TOME(ItemID.SHAMANS_TOME),
    SINKETHS_DIARY(ItemID.SINKETHS_DIARY),
    SOGGY_JOURNAL(ItemID.SOGGY_JOURNAL),
    SOUL_WARS_GUIDE(ItemID.SOUL_WARS_GUIDE),
    SPIRIT_ANGLERS_RESEARCH_NOTES(ItemID.SPIRIT_ANGLERS_RESEARCH_NOTES),
    STAINED_JOURNAL(ItemID.STAINED_JOURNAL),
    STRANGE_HALLOWED_TOME(ItemID.STRANGE_HALLOWED_TOME),
    STRONGHOLD_NOTES(ItemID.STRONGHOLD_NOTES),
    TARNS_DIARY(ItemID.TARNS_DIARY),
    TEKTONS_JOURNAL(ItemID.TEKTONS_JOURNAL),
    THE_BUTCHER(ItemID.THE_BUTCHER),
    THE_DESERT_TROUT__SHIPS_LOG(ItemID.THE_DESERT_TROUT__SHIPS_LOG),
    THE_EIGHT_CLANS(ItemID.THE_EIGHT_CLANS),
    THE_GREAT_DIVIDE(ItemID.THE_GREAT_DIVIDE),
    THE_HUEYCOATL(ItemID.THE_HUEYCOATL),
    THE_JACKALS_TORCH(ItemID.THE_JACKALS_TORCH),
    THE_LIVING_STATUES(ItemID.THE_LIVING_STATUES),
    THE_SHADOW_REALM(ItemID.THE_SHADOW_REALM),
    THE_SLEEPING_SEVEN(ItemID.THE_SLEEPING_SEVEN),
    THE_SPURNED_DEMON(ItemID.THE_SPURNED_DEMON),
    THE_TRUTH_BEHIND_THE_MYTH_EXCERPT(ItemID.THE_TRUTH_BEHIND_THE_MYTH_EXCERPT),
    THE_WARDENS(ItemID.THE_WARDENS),
    THE_WEEPING(ItemID.THE_WEEPING),
    THE_WILD_HUNT(ItemID.THE_WILD_HUNT),
    TOME_OF_THE_MOON(ItemID.TOME_OF_THE_MOON),
    TOME_OF_THE_SUN(ItemID.TOME_OF_THE_SUN),
    TOME_OF_THE_TEMPLE(ItemID.TOME_OF_THE_TEMPLE),
    TRANSDIMENSIONAL_NOTES(ItemID.TRANSDIMENSIONAL_NOTES),
    TRANSLATION(ItemID.TRANSLATION),
    TRANSLATION_BOOK(ItemID.TRANSLATION_BOOK),
    TREE_WIZARDS_JOURNAL(ItemID.TREE_WIZARDS_JOURNAL),
    UNGAEL_LAB_NOTES(ItemID.UNGAEL_LAB_NOTES),
    VANGUARD_JUDGEMENT(ItemID.VANGUARD_JUDGEMENT),
    VARLAMORE_ENVOY(ItemID.VARLAMORE_ENVOY),
    VARMENS_NOTES(ItemID.VARMENS_NOTES),
    VERZIK_VITUR__PATIENT_RECORD(ItemID.VERZIK_VITUR__PATIENT_RECORD),
    WEISS_FIRE_NOTES(ItemID.WEISS_FIRE_NOTES),
    YEWNOCKS_NOTES(ItemID.YEWNOCKS_NOTES);

    private final int itemID;
    @Getter
    private final String location = "Bookcase";

    @Getter
    private final boolean isBis;

    Bookcase(int itemID)
    {
        this.itemID = itemID;
        this.isBis = false;
    }
}
