/*
 * BSD 2-Clause License
 *
 * Copyright (c) 2021, Riley McGee
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.wastedbankspace.model.locations;

import com.wastedbankspace.model.StorageLocation;
import net.runelite.api.ItemID;

import java.util.Set;

public class MagicWardrobe implements StorageLocation {

    private static final Set<Integer> ITEMS = Set.of(
            ItemID.AMYS_SAW,
            ItemID.ANCESTRAL_HAT,
            ItemID.ANCESTRAL_ROBE_BOTTOM,
            ItemID.ANCESTRAL_ROBE_TOP,
            ItemID.TWISTED_ANCESTRAL_HAT,
            ItemID.TWISTED_ANCESTRAL_ROBE_BOTTOM,
            ItemID.TWISTED_ANCESTRAL_ROBE_TOP,
            ItemID.BLOODBARK_BODY,
            ItemID.BLOODBARK_BOOTS,
            ItemID.BLOODBARK_HELM,
            ItemID.BLOODBARK_LEGS,
            ItemID.BLOODBARK_GAUNTLETS,
            ItemID.BOUNTY_HUNTER_HAT_TIER_1,
            ItemID.BOUNTY_HUNTER_HAT_TIER_2,
            ItemID.BOUNTY_HUNTER_HAT_TIER_3,
            ItemID.BOUNTY_HUNTER_HAT_TIER_4,
            ItemID.BOUNTY_HUNTER_HAT_TIER_5,
            ItemID.BOUNTY_HUNTER_HAT_TIER_6,
            ItemID.BRUMA_TORCH,
            ItemID.CARPENTERS_BOOTS,
            ItemID.CARPENTERS_HELMET,
            ItemID.CARPENTERS_SHIRT,
            ItemID.CARPENTERS_TROUSERS,
            ItemID.DAGONHAI_HAT,
            ItemID.DAGONHAI_ROBE_TOP,
            ItemID.DAGONHAI_ROBE_BOTTOM,
            ItemID.DARK_FLIPPERS,
            ItemID.ELDER_CHAOS_HOOD,
            ItemID.ELDER_CHAOS_ROBE,
            ItemID.ELDER_CHAOS_TOP,
            ItemID.EVIL_CHICKEN_FEET,
            ItemID.EVIL_CHICKEN_HEAD,
            ItemID.EVIL_CHICKEN_LEGS,
            ItemID.EVIL_CHICKEN_WINGS,
            ItemID.BRONZE_FIST_FLAG,
            ItemID.CUTTHROAT_FLAG,
            ItemID.GILDED_SMILE_FLAG,
            ItemID.LUCKY_SHOT_FLAG,
            ItemID.PHASMATYS_FLAG,
            ItemID.GHOSTLY_BOOTS,
            ItemID.GHOSTLY_CLOAK,
            ItemID.GHOSTLY_HOOD,
            ItemID.GHOSTLY_ROBE,
            ItemID.GHOSTLY_GLOVES,
            ItemID.GHOSTLY_ROBE_6108,
            //GRACEFUL
            ItemID.IMCANDO_HAMMER,
            ItemID.INFINITY_BOOTS,
            ItemID.INFINITY_BOTTOMS,
            ItemID.INFINITY_HAT,
            ItemID.INFINITY_TOP,
            ItemID.INFINITY_GLOVES,
            ItemID.DARK_INFINITY_BOTTOMS,
            ItemID.DARK_INFINITY_HAT,
            ItemID.DARK_INFINITY_TOP,
            ItemID.LIGHT_INFINITY_BOTTOMS,
            ItemID.LIGHT_INFINITY_HAT,
            ItemID.LIGHT_INFINITY_TOP,
            ItemID.LUNAR_HELM,
            ItemID.LUNAR_CAPE,
            ItemID.LUNAR_AMULET,
            ItemID.LUNAR_BOOTS,
            ItemID.LUNAR_GLOVES,
            ItemID.LUNAR_LEGS,
            ItemID.LUNAR_RING,
            ItemID.LUNAR_TORSO,
            ItemID.MOONCLAN_HELM,
            ItemID.MOONCLAN_CAPE,
            ItemID.MOONCLAN_BOOTS,
            ItemID.MOONCLAN_GLOVES,
            ItemID.MOONCLAN_ARMOUR,
            ItemID.MOONCLAN_SKIRT,
            ItemID.MUDSKIPPER_HAT,
            ItemID.FLIPPERS,
            ItemID.MYSTIC_BOOTS,
            ItemID.MYSTIC_HAT,
            ItemID.MYSTIC_ROBE_BOTTOM,
            ItemID.MYSTIC_ROBE_TOP,
            ItemID.MYSTIC_GLOVES,
            ItemID.MYSTIC_BOOTS_DARK,
            ItemID.MYSTIC_HAT_DARK,
            ItemID.MYSTIC_ROBE_BOTTOM_DARK,
            ItemID.MYSTIC_ROBE_TOP_DARK,
            ItemID.MYSTIC_GLOVES_DARK,
            ItemID.MYSTIC_BOOTS_LIGHT,
            ItemID.MYSTIC_HAT_LIGHT,
            ItemID.MYSTIC_ROBE_BOTTOM_LIGHT,
            ItemID.MYSTIC_ROBE_TOP_LIGHT,
            ItemID.MYSTIC_GLOVES_LIGHT,
            ItemID.MYSTIC_BOOTS_DUSK,
            ItemID.MYSTIC_HAT_DUSK,
            ItemID.MYSTIC_ROBE_BOTTOM_DUSK,
            ItemID.MYSTIC_ROBE_TOP_DUSK,
            ItemID.MYSTIC_GLOVES_DUSK,
            ItemID.MYSTIC_BOOTS_OR,
            ItemID.MYSTIC_HAT_OR,
            ItemID.MYSTIC_ROBE_BOTTOM_OR,
            ItemID.MYSTIC_ROBE_TOP_OR,
            ItemID.MYSTIC_GLOVES_OR,
            ItemID.BLACK_NAVAL_SHIRT,
            ItemID.BLACK_NAVY_SLACKS,
            ItemID.BLACK_TRICORN_HAT,
            ItemID.BLUE_NAVAL_SHIRT,
            ItemID.BLUE_NAVY_SLACKS,
            ItemID.BLUE_TRICORN_HAT,
            ItemID.BROWN_NAVAL_SHIRT,
            ItemID.BROWN_NAVY_SLACKS,
            ItemID.BROWN_TRICORN_HAT,
            ItemID.GREEN_NAVAL_SHIRT,
            ItemID.GREEN_NAVY_SLACKS,
            ItemID.GREEN_TRICORN_HAT,
            ItemID.GREY_NAVAL_SHIRT,
            ItemID.GREY_NAVY_SLACKS,
            ItemID.GREY_TRICORN_HAT,
            ItemID.PURPLE_NAVAL_SHIRT,
            ItemID.PURPLE_NAVY_SLACKS,
            ItemID.PURPLE_TRICORN_HAT,
            ItemID.RED_NAVAL_SHIRT,
            ItemID.RED_NAVY_SLACKS,
            ItemID.RED_TRICORN_HAT,
            ItemID.OILY_PEARL_FISHING_ROD,
            ItemID.PEARL_BARBARIAN_ROD,
            ItemID.PEARL_FISHING_ROD,
            ItemID.PEARL_FLY_FISHING_ROD,
            ItemID.PYROMANCER_BOOTS,
            ItemID.PYROMANCER_GARB,
            ItemID.PYROMANCER_HOOD,
            ItemID.PYROMANCER_ROBE,
            ItemID.SKELETAL_HELM,
            ItemID.SKELETAL_BOTTOMS,
            ItemID.SKELETAL_BOOTS,
            ItemID.SKELETAL_GLOVES,
            ItemID.SKELETAL_TOP,
            ItemID.SMITHS_TUNIC,
            ItemID.SMITHS_TROUSERS,
            ItemID.SMITHS_GLOVES,
            ItemID.SMITHS_GLOVES_I,
            ItemID.SMITHS_BOOTS,
            ItemID.SPLITBARK_BODY,
            ItemID.SPLITBARK_BOOTS,
            ItemID.SPLITBARK_HELM,
            ItemID.SPLITBARK_LEGS,
            ItemID.SPLITBARK_GAUNTLETS,
            ItemID.SWAMPBARK_BODY,
            ItemID.SWAMPBARK_BOOTS,
            ItemID.SWAMPBARK_HELM,
            ItemID.SWAMPBARK_LEGS,
            ItemID.SWAMPBARK_GAUNTLETS,
            ItemID.VILLAGER_ARMBAND,
            ItemID.VILLAGER_ARMBAND_6359,
            ItemID.VILLAGER_ARMBAND_6369,
            ItemID.VILLAGER_ARMBAND_6379,
            ItemID.VILLAGER_HAT,
            ItemID.VILLAGER_HAT_6355,
            ItemID.VILLAGER_HAT_6365,
            ItemID.VILLAGER_HAT_6375,
            ItemID.VILLAGER_ROBE,
            ItemID.VILLAGER_ROBE_6353,
            ItemID.VILLAGER_ROBE_6363,
            ItemID.VILLAGER_ROBE_6373,
            ItemID.VILLAGER_SANDALS,
            ItemID.VILLAGER_SANDALS_6357,
            ItemID.VILLAGER_SANDALS_6367,
            ItemID.VILLAGER_SANDALS_6377,
            ItemID.TRIBAL_TOP,
            ItemID.TRIBAL_TOP_6351,
            ItemID.TRIBAL_TOP_6361,
            ItemID.TRIBAL_TOP_6371,
            ItemID.WARM_GLOVES,
            ItemID.ZEALOTS_BOOTS,
            ItemID.ZEALOTS_HELM,
            ItemID.ZEALOTS_ROBE_BOTTOM,
            ItemID.ZEALOTS_ROBE_TOP,
            ItemID.HOOD_OF_RUIN,
            ItemID.ROBE_TOP_OF_RUIN,
            ItemID.ROBE_BOTTOM_OF_RUIN,
            ItemID.GLOVES_OF_RUIN,
            ItemID.SOCKS_OF_RUIN,
            ItemID.CLOAK_OF_RUIN,
            ItemID.HAT_OF_THE_EYE,
            ItemID.ROBE_TOP_OF_THE_EYE,
            ItemID.ROBE_BOTTOMS_OF_THE_EYE,
            ItemID.BOOTS_OF_THE_EYE,
            ItemID.HAT_OF_THE_EYE_BLUE,
            ItemID.ROBE_TOP_OF_THE_EYE_BLUE,
            ItemID.ROBE_BOTTOMS_OF_THE_EYE_BLUE,
            ItemID.HAT_OF_THE_EYE_RED,
            ItemID.ROBE_TOP_OF_THE_EYE_RED,
            ItemID.ROBE_BOTTOMS_OF_THE_EYE_RED,
            ItemID.HAT_OF_THE_EYE_GREEN,
            ItemID.ROBE_TOP_OF_THE_EYE_GREEN,
            ItemID.ROBE_BOTTOMS_OF_THE_EYE_GREEN,
            ItemID.PHEASANT_HAT,
            ItemID.PHEASANT_CAPE,
            ItemID.PHEASANT_LEGS,
            ItemID.PHEASANT_BOOTS,
            ItemID.LOG_BASKET,
            ItemID.FORESTRY_KIT,
            ItemID.VIRTUS_MASK,
            ItemID.VIRTUS_ROBE_BOTTOM,
            ItemID.VIRTUS_ROBE_TOP,
            ItemID.DARK_SQUALL_HOOD,
            ItemID.DARK_SQUALL_ROBE_TOP,
            ItemID.DARK_SQUALL_ROBE_BOTTOM,
            ItemID.EMISSARY_HOOD,
            ItemID.EMISSARY_ROBE_TOP,
            ItemID.EMISSARY_ROBE_BOTTOM,
            ItemID.EMISSARY_SANDALS,
            ItemID.MASK_OF_REBIRTH,
            ItemID.ANCIENT_CEREMONIAL_BOOTS,
            ItemID.ANCIENT_CEREMONIAL_GLOVES,
            ItemID.ANCIENT_CEREMONIAL_MASK,
            ItemID.ANCIENT_CEREMONIAL_LEGS,
            ItemID.ANCIENT_CEREMONIAL_TOP
    );

    @Override
    public String getName() {
        return "Magic Wardrobe";
    }

    @Override
    public Set<Integer> getStorableItems() {
        return ITEMS;
    }
}
