/*
 * BSD 2-Clause License
 *
 * Copyright (c) 2021, Riley McGee
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.wastedbankspace.model.locations;

import com.wastedbankspace.model.StorableItem;
import lombok.Getter;
import net.runelite.api.Item;
import net.runelite.api.ItemID;

@Getter
public enum PetHouse implements StorableItem {
    PET_CHAOS_ELEMENTAL(ItemID.PET_CHAOS_ELEMENTAL),
    PET_DAGANNOTH_SUPREME(ItemID.PET_DAGANNOTH_SUPREME),
    PET_DAGANNOTH_PRIME(ItemID.PET_DAGANNOTH_PRIME),
    PET_DAGANNOTH_REX(ItemID.PET_DAGANNOTH_REX),
    PET_PENANCE_QUEEN(ItemID.PET_PENANCE_QUEEN),
    PET_KREEARRA(ItemID.PET_KREEARRA),
    PET_GENERAL_GRAARDOR(ItemID.PET_GENERAL_GRAARDOR),
    PET_ZILYANA(ItemID.PET_ZILYANA),
    PET_KRIL_TSUTAROTH(ItemID.PET_KRIL_TSUTSAROTH),
    PET_BABY_MOLE(ItemID.BABY_MOLE),
    PET_PRINCE_BLACK_DRAGON(ItemID.PRINCE_BLACK_DRAGON),
    PET_KALPHITE_PRINCESS(ItemID.KALPHITE_PRINCESS),
    PET_SMOKE_DEVIL(ItemID.PET_SMOKE_DEVIL),
    PET_KRAKEN(ItemID.PET_KRAKEN),
    PET_DARK_CORE(ItemID.PET_DARK_CORE),
    PET_SNAKELING(ItemID.PET_SNAKELING),
    CHOMPY_CHICK(ItemID.CHOMPY_CHICK),
    VENENATIS_SPIDERLING(ItemID.VENENATIS_SPIDERLING),
    CALLISTO_CUB(ItemID.CALLISTO_CUB),
    CALLISTO_CUB_(ItemID.CALLISTO_CUB_27649),
    VETION_JR(ItemID.VETION_JR),
    SCORPIAS_OFFSPRING(ItemID.SCORPIAS_OFFSPRING),
    TZREKJAD(ItemID.TZREKJAD),
    HELLPUPPY(ItemID.HELLPUPPY),
    ABYSSAL_ORPHAN(ItemID.ABYSSAL_ORPHAN),
    HERON(ItemID.HERON),
    ROCK_GOLEM(ItemID.ROCK_GOLEM),
    BEAVER(ItemID.BEAVER),
    BABY_CHINCHOMPA(ItemID.BABY_CHINCHOMPA),
    BLOODHOUND(ItemID.BLOODHOUND),
    GIANT_SQUIRREL(ItemID.GIANT_SQUIRREL),
    TANGLEROOT(ItemID.TANGLEROOT),
    RIFT_GUARDIAN(ItemID.RIFT_GUARDIAN),
    ROCKY(ItemID.ROCKY),
    PHOENIX(ItemID.PHOENIX),
    OLMLET(ItemID.OLMLET),
    SKOTOS(ItemID.SKOTOS),
    JALNIBREK(ItemID.JALNIBREK),
    HERBI(ItemID.HERBI),
    NOON(ItemID.NOON),
    VORKI(ItemID.VORKI),
    LIL_ZIK(ItemID.LIL_ZIK),
    IKKLE_HYDRA(ItemID.IKKLE_HYDRA),
    SRARACHA(ItemID.SRARACHA),
    YOUNGLLEF(ItemID.YOUNGLLEF),
    SMOLCANO(ItemID.SMOLCANO),
    LITTLE_NIGHTMARE(ItemID.LITTLE_NIGHTMARE),
    LIL_CREATOR(ItemID.LIL_CREATOR),
    TINY_TEMPOR(ItemID.TINY_TEMPOR),
    NEXLING(ItemID.NEXLING),
    ABYSSAL_PROTECTOR(ItemID.ABYSSAL_PROTECTOR),
    TUMEKENS_GUARDIAN(ItemID.TUMEKENS_GUARDIAN),
    MUPHIN(ItemID.MUPHIN),
    WISP(ItemID.WISP),
    BUTCH(ItemID.BUTCH),
    LILVIATHAN(ItemID.LILVIATHAN),
    BARON(ItemID.BARON),
    SCURRY(ItemID.SCURRY),
    SMOL_HEREDIT(ItemID.SMOL_HEREDIT),
    QUETZIN(ItemID.QUETZIN),
    NID(ItemID.NID),
    HUBERTE(ItemID.HUBERTE),
    MOXI(ItemID.MOXI),

    // Extras
    PET_KITTEN(ItemID.PET_KITTEN),
    PET_KITTEN_1556(ItemID.PET_KITTEN_1556),
    PET_KITTEN_1557(ItemID.PET_KITTEN_1557),
    PET_KITTEN_1558(ItemID.PET_KITTEN_1558),
    PET_KITTEN_1559(ItemID.PET_KITTEN_1559),
    PET_KITTEN_1560(ItemID.PET_KITTEN_1560),
    PET_CAT(ItemID.PET_CAT),
    PET_CAT_1562(ItemID.PET_CAT_1562),
    PET_CAT_1563(ItemID.PET_CAT_1563),
    PET_CAT_1564(ItemID.PET_CAT_1564),
    PET_CAT_1565(ItemID.PET_CAT_1565),
    PET_CAT_1566(ItemID.PET_CAT_1566),
    PET_CAT_1567(ItemID.PET_CAT_1567), // overgrown
    PET_CAT_1568(ItemID.PET_CAT_1568), // overgrown
    PET_CAT_1569(ItemID.PET_CAT_1569), // overgrown
    PET_CAT_1570(ItemID.PET_CAT_1570), // overgrown
    PET_CAT_1571(ItemID.PET_CAT_1571), // overgrown
    PET_CAT_1572(ItemID.PET_CAT_1572), // overgrown
    WILY_CAT(ItemID.WILY_CAT),
    WILY_CAT_6556(ItemID.WILY_CAT_6556),
    WILY_CAT_6557(ItemID.WILY_CAT_6557),
    WILY_CAT_6558(ItemID.WILY_CAT_6558),
    WILY_CAT_6559(ItemID.WILY_CAT_6559),
    WILY_CAT_6560(ItemID.WILY_CAT_6560),
    LAZY_CAT(ItemID.LAZY_CAT),
    LAZY_CAT_6550(ItemID.LAZY_CAT_6550),
    LAZY_CAT_6551(ItemID.LAZY_CAT_6551),
    LAZY_CAT_6552(ItemID.LAZY_CAT_6552),
    LAZY_CAT_6553(ItemID.LAZY_CAT_6553),
    LAZY_CAT_6554(ItemID.LAZY_CAT_6554),
    HELLKITTEN(ItemID.HELLKITTEN),
    HELL_CAT(ItemID.HELL_CAT),
    OVERGROWN_HELLCAT(ItemID.OVERGROWN_HELLCAT),
    WILY_HELLCAT(ItemID.WILY_HELLCAT),
    LAZY_HELL_CAT(ItemID.LAZY_HELL_CAT),
    TOY_CAT(ItemID.TOY_CAT),
    FISHBOWL_6670(ItemID.FISHBOWL_6670),
    FISHBOWL_6671(ItemID.FISHBOWL_6671),
    FISHBOWL_6672(ItemID.FISHBOWL_6672),
    PET_ROCK(ItemID.PET_ROCK),
    BROAV(ItemID.BROAV);

    private final int itemID;
    @Getter
    private final String location = "Pet House";
    @Getter
    private final boolean isBis;
    PetHouse(int itemID) {
        this.itemID = itemID;
        this.isBis = false;
    }
}
