/*
 * BSD 2-Clause License
 *
 * Copyright (c) 2021, Riley McGee
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.wastedbankspace.model.locations;

import com.wastedbankspace.model.StorageLocation;
import lombok.Getter;
import net.runelite.api.ItemID;

import java.util.Set;

public class ToyBox implements StorageLocation {

    private static final Set<Integer> ITEMS = Set.of(
            ItemID.BUNNY_EARS,
            ItemID.SCYTHE,
            ItemID.YOYO,
            ItemID.EASTER_BASKET,
            ItemID.RED_MARIONETTE,
            ItemID.BLUE_MARIONETTE,
            ItemID.GREEN_MARIONETTE,
            ItemID.RUBBER_CHICKEN,
            ItemID.BOBBLE_HAT,
            ItemID.JESTER_HAT,
            ItemID.TRIJESTER_HAT,
            ItemID.WOOLLY_HAT,
            ItemID.BOBBLE_SCARF,
            ItemID.JESTER_SCARF,
            ItemID.TRIJESTER_SCARF,
            ItemID.WOOLLY_SCARF,
            ItemID.ZOMBIE_HEAD,
            ItemID.JACK_LANTERN_MASK,
            ItemID.REINDEER_HAT,
            ItemID.EASTER_RING,
            ItemID.SKELETON_MASK,
            ItemID.SKELETON_SHIRT,
            ItemID.SKELETON_LEGGINGS,
            ItemID.SKELETON_GLOVES,
            ItemID.SKELETON_BOOTS,
            ItemID.CHICKEN_HEAD,
            ItemID.CHICKEN_WINGS,
            ItemID.CHICKEN_LEGS,
            ItemID.CHICKEN_FEET,
            ItemID.GRIM_REAPER_HOOD,
            ItemID.BLACK_HWEEN_MASK,
            ItemID.BLACK_PARTYHAT,
            ItemID.RAINBOW_PARTYHAT,
            ItemID.COW_MASK,
            ItemID.COW_TOP,
            ItemID.COW_TROUSERS,
            ItemID.COW_GLOVES,
            ItemID.COW_SHOES,
            ItemID.ANTISANTA_MASK,
            ItemID.ANTISANTA_JACKET,
            ItemID.ANTISANTA_PANTALOONS,
            ItemID.ANTISANTA_GLOVES,
            ItemID.ANTISANTA_BOOTS,
            ItemID.DRUIDIC_WREATH,
            ItemID.SANTA_MASK,
            ItemID.SANTA_JACKET,
            ItemID.SANTA_PANTALOONS,
            ItemID.SANTA_GLOVES,
            ItemID.SANTA_BOOTS,
            ItemID.BUNNY_TOP,
            ItemID.BUNNY_LEGS,
            ItemID.BUNNY_PAWS,
            ItemID.BUNNY_FEET,
            ItemID.ANTIPANTIES,
            ItemID.BLACK_SANTA_HAT,
            ItemID.INVERTED_SANTA_HAT,
            ItemID.MASK_OF_BALANCE,
            ItemID.TIGER_TOY,
            ItemID.LION_TOY,
            ItemID.SNOW_LEOPARD_TOY,
            ItemID.AMUR_LEOPARD_TOY,
            ItemID.GRAVEDIGGER_MASK,
            ItemID.GRAVEDIGGER_TOP,
            ItemID.GRAVEDIGGER_LEGGINGS,
            ItemID.GRAVEDIGGER_GLOVES,
            ItemID.GRAVEDIGGER_BOOTS,
            ItemID.CABBAGE_CAPE,
            ItemID.CRUCIFEROUS_CODEX,
            ItemID.GIANT_PRESENT,
            ItemID.GNOME_CHILD_HAT,
            ItemID.HORNWOOD_HELM,
            ItemID.BANSHEE_MASK,
            ItemID.BANSHEE_TOP,
            ItemID.BANSHEE,
            ItemID.HUNTING_KNIFE,
            ItemID.SACK_OF_PRESENTS,
            ItemID.SNOW_GLOBE,
            ItemID._4TH_BIRTHDAY_HAT,
            ItemID.BIRTHDAY_BALLOONS,
            ItemID.EASTER_EGG_HELM,
            ItemID.HAND_FAN,
            ItemID.JONAS_MASK,
            ItemID.RAINBOW_SCARF,
            ItemID.RUNEFEST_SHIELD,
            ItemID.SNOW_IMP_COSTUME_HEAD,
            ItemID.SNOW_IMP_COSTUME_BODY,
            ItemID.SNOW_IMP_COSTUME_LEGS,
            ItemID.SNOW_IMP_COSTUME_TAIL,
            ItemID.SNOW_IMP_COSTUME_GLOVES,
            ItemID.SNOW_IMP_COSTUME_FEET,
            ItemID.WISE_OLD_MANS_SANTA_HAT,
            ItemID.PROP_SWORD,
            ItemID.STARFACE,
            ItemID.TREE_TOP,
            ItemID.TREE_SKIRT,
            ItemID.CANDY_CANE,
            ItemID.CLOWN_MASK,
            ItemID.CLOWN_GOWN,
            ItemID.CLOWN_BOW_TIE,
            ItemID.CLOWN_TROUSERS,
            ItemID.CLOWN_SHOES,
            ItemID.EEK,
            ItemID.EGGSHELL_PLATEBODY,
            ItemID.EGGSHELL_PLATELEGS,
            ItemID.BIRTHDAY_CAKE,
            ItemID.BUNNYMAN_MASK,
            ItemID.GIANT_EASTER_EGG,
            ItemID.GREEN_GINGERBREAD_SHIELD,
            ItemID.PUMPKIN_LANTERN,
            ItemID.SKELETON_LANTERN,
            ItemID.SPOOKIER_HOOD,
            ItemID.SPOOKIER_ROBE,
            ItemID.SPOOKIER_SKIRT,
            ItemID.SPOOKIER_GLOVES,
            ItemID.SPOOKIER_BOOTS,
            ItemID.SPOOKY_HOOD,
            ItemID.SPOOKY_ROBE,
            ItemID.SPOOKY_SKIRT,
            ItemID.SPOOKY_GLOVES,
            ItemID.SPOOKY_BOOTS,
            ItemID.CAT_EARS,
            ItemID.GIANT_BOULDER,
            ItemID.CARROT_SWORD,
            ItemID._24CARAT_SWORD,
            ItemID.MAGIC_EGG_BALL,
            ItemID.GOBLIN_DECORATIONS,
            ItemID.HEADLESS_HEAD,
            ItemID.MAGICAL_PUMPKIN,
            ItemID._20TH_ANNIVERSARY_HAT,
            ItemID._20TH_ANNIVERSARY_TOP,
            ItemID._20TH_ANNIVERSARY_BOTTOM,
            ItemID._20TH_ANNIVERSARY_NECKLACE,
            ItemID._20TH_ANNIVERSARY_CAPE,
            ItemID._20TH_ANNIVERSARY_GLOVES,
            ItemID._20TH_ANNIVERSARY_BOOTS,
            ItemID.BANANA_CAPE,
            ItemID.BANANA_HAT,
            ItemID.CURSED_BANANA,
            ItemID.FESTIVE_ELF_HAT,
            ItemID.FESTIVE_ELF_SLIPPERS,
            ItemID.GNOME_CHILD_MASK,
            ItemID.GNOME_CHILD_ICON,
            ItemID.GREGGS_EASTDOOR,
            ItemID.HAUNTED_WINE_BOTTLE,
            ItemID.SNOWMAN_RING,
            ItemID.PROPELLER_HAT,
            ItemID.SAUCEPAN,
            ItemID.SECRET_SANTA_PRESENT_RED,
            ItemID.SECRET_SANTA_PRESENT_BLUE,
            ItemID.SECRET_SANTA_PRESENT_GREEN,
            ItemID.SECRET_SANTA_PRESENT_BLACK,
            ItemID.SECRET_SANTA_PRESENT_GOLD,
            ItemID.UGLY_HALLOWEEN_JUMPER_ORANGE,
            ItemID.UGLY_HALLOWEEN_JUMPER_BLACK,
            ItemID.SACK_OF_COAL,
            ItemID.CRATE_RING,
            ItemID.EASTER_HAT,
            ItemID.FESTIVE_GAMES_CROWN,
            ItemID.CHRISTMAS_JUMPER,
            ItemID.HALLOWEEN_WIG,
            ItemID.HALLOWEEN_WIG_27499,
            ItemID.HALLOWEEN_WIG_27501,
            ItemID.HALLOWEEN_WIG_27503,
            ItemID.HALLOWEEN_WIG_27505,
            ItemID.HALLOWEEN_WIG_27507,
            ItemID.FESTIVE_NUTCRACKER_HAT,
            ItemID.FESTIVE_NUTCRACKER_TOP,
            ItemID.FESTIVE_NUTCRACKER_TROUSERS,
            ItemID.FESTIVE_NUTCRACKER_BOOTS,
            ItemID.FESTIVE_NUTCRACKER_STAFF,
            ItemID.SWEET_NUTCRACKER_HAT,
            ItemID.SWEET_NUTCRACKER_TOP,
            ItemID.SWEET_NUTCRACKER_TROUSERS,
            ItemID.SWEET_NUTCRACKER_BOOTS,
            ItemID.SWEET_NUTCRACKER_STAFF,
            ItemID.FLOWER_CROWN,
            ItemID.FLOWER_CROWN_27141,
            ItemID.FLOWER_CROWN_27143,
            ItemID.FLOWER_CROWN_27145,
            ItemID.FLOWER_CROWN_27147,
            ItemID.FLOWER_CROWN_27149,
            ItemID.FLOWER_CROWN_27151,
            ItemID.FLOWER_CROWN_27153,
            ItemID.FLOWER_CROWN_27155,
            ItemID.SKIS,
            ItemID.SANTAS_LIST,
            ItemID.SNOW_GOGGLES__HAT,
            ItemID.TREAT_CAULDRON,
            ItemID.TREAT_CAULDRON_27465,
            ItemID.TREAT_CAULDRON_27467,
            ItemID.TREAT_CAULDRON_27469,
            ItemID.TREAT_CAULDRON_27471,
            ItemID.WITCH_HAT,
            ItemID.WITCH_TOP,
            ItemID.WITCH_ROBES,
            ItemID.WITCH_BOOTS,
            ItemID.WITCH_CAPE,
            ItemID._10TH_BIRTHDAY_CAPE,
            ItemID._10TH_BIRTHDAY_BALLOONS,
            ItemID.CAKE_HAT,
            ItemID.OLDSCHOOL_JUMPER,
            ItemID.OLDSCHOOL_JUMPER_27823,
            ItemID.OLDSCHOOL_JUMPER_27824,
            ItemID.OLDSCHOOL_JUMPER_27825,
            ItemID.OLDSCHOOL_JUMPER_27826,
            ItemID.OLDSCHOOL_JUMPER_27827,
            ItemID.GNOME_CHILD_PLUSH,
            ItemID.STRAY_DOG_PLUSH,
            ItemID.JAD_PLUSH,
            ItemID.BOB_THE_CAT_SLIPPERS,
            ItemID.JAD_SLIPPERS,
            ItemID.DRAGON_CANDLE_DAGGER,
            ItemID.GNOME_CHILD_BACKPACK,
            ItemID.MYSTIC_CARDS,
            ItemID.SILVER_PARTYHAT,
            ItemID.WAR_SHIP,
            ItemID.GIANT_BRONZE_DAGGER,
            ItemID.EASTFLOOR_SPADE,
            ItemID.NEST_HAT,
            ItemID.NEST_HAT_27877,
            ItemID.COLOURFUL_CAPE,
            ItemID.COLOURFUL_CAPE_29493,
            ItemID.COLOURFUL_CAPE_29497,
            ItemID.COLOURFUL_CAPE_29501,
            ItemID.COLOURFUL_CAPE_29495,
            ItemID.COLOURFUL_CAPE_29499,
            ItemID.COLOURFUL_CAPE_29503,
            ItemID.COLOURFUL_CAPE_29505,
            ItemID.RAINBOW_CAPE,
            ItemID.RAINBOW_CROWN_SHIRT,
            ItemID.COLOURFUL_CROWN_SHIRT,
            ItemID.COLOURFUL_CROWN_SHIRT_29510,
            ItemID.COLOURFUL_CROWN_SHIRT_29511,
            ItemID.COLOURFUL_CROWN_SHIRT_29512,
            ItemID.COLOURFUL_CROWN_SHIRT_29513,
            ItemID.COLOURFUL_CROWN_SHIRT_29514,
            ItemID.COLOURFUL_CROWN_SHIRT_29515,
            ItemID.COLOURFUL_CROWN_SHIRT_29516
    );

    @Override
    public String getName() {
        return "Toy Box";
    }

    @Override
    public Set<Integer> getStorableItems() {
        return ITEMS;
    }
}
