package com.wastedbankspace.locations;

import com.wastedbankspace.model.StorableItem;
import lombok.Getter;
import net.runelite.api.ItemID;

@Getter
public enum FossilStorage implements StorableItem {
    UNIDENTIFIED_SMALL_FOSSIL(ItemID.UNIDENTIFIED_SMALL_FOSSIL),
    SMALL_FOSSILISED_LIMBS(ItemID.SMALL_FOSSILISED_LIMBS),
    SMALL_FOSSILISED_SPINE(ItemID.SMALL_FOSSILISED_SPINE),
    SMALL_FOSSILISED_RIBS(ItemID.SMALL_FOSSILISED_RIBS),
    SMALL_FOSSILISED_PELVIS(ItemID.SMALL_FOSSILISED_PELVIS),
    SMALL_FOSSILISED_SKULL(ItemID.SMALL_FOSSILISED_SKULL),
    UNIDENTIFIED_MEDIUM_FOSSIL(ItemID.UNIDENTIFIED_MEDIUM_FOSSIL),
    MEDIUM_FOSSILISED_LIMBS(ItemID.MEDIUM_FOSSILISED_LIMBS),
    MEDIUM_FOSSILISED_SPINE(ItemID.MEDIUM_FOSSILISED_SPINE),
    MEDIUM_FOSSILISED_RIBS(ItemID.MEDIUM_FOSSILISED_RIBS),
    MEDIUM_FOSSILISED_PELVIS(ItemID.MEDIUM_FOSSILISED_PELVIS),
    MEDIUM_FOSSILISED_SKULL(ItemID.MEDIUM_FOSSILISED_SKULL),
    UNIDENTIFIED_LARGE_FOSSIL(ItemID.UNIDENTIFIED_LARGE_FOSSIL),
    LARGE_FOSSILISED_LIMBS(ItemID.LARGE_FOSSILISED_LIMBS),
    LARGE_FOSSILISED_SPINE(ItemID.LARGE_FOSSILISED_SPINE),
    LARGE_FOSSILISED_RIBS(ItemID.LARGE_FOSSILISED_RIBS),
    LARGE_FOSSILISED_PELVIS(ItemID.LARGE_FOSSILISED_PELVIS),
    LARGE_FOSSILISED_SKULL(ItemID.LARGE_FOSSILISED_SKULL),
    FOSSILISED_ROOTS(ItemID.FOSSILISED_ROOTS),
    FOSSILISED_STUMP(ItemID.FOSSILISED_STUMP),
    FOSSILISED_BRANCH(ItemID.FOSSILISED_BRANCH),
    FOSSILISED_LEAF(ItemID.FOSSILISED_LEAF),
    FOSSILISED_MUSHROOM(ItemID.FOSSILISED_MUSHROOM);

    private final int itemID;
    @Getter
    private final String location = "Fossil Storage";

    FossilStorage(int itemID) {
        this.itemID = itemID;
    }
}
